#!/bin/bash
# Script to help configure Railway deployment
# This script provides instructions - Railway root directory must be set in dashboard

echo "=========================================="
echo "Railway Deployment Configuration Helper"
echo "=========================================="
echo ""
echo "CRITICAL: Railway Service Root Directory must be set manually"
echo ""
echo "Steps to fix deployment:"
echo ""
echo "1. Go to Railway Dashboard:"
echo "   https://railway.com/project/8ef4265a-363c-497d-878d-859de8b4b25a/service/24df0070-1606-4993-89aa-9da987f2643a"
echo ""
echo "2. Click 'Settings' tab"
echo ""
echo "3. Find 'Root Directory' setting"
echo ""
echo "4. Set it to: server"
echo "   (without quotes, without leading slash)"
echo ""
echo "5. Click 'Save'"
echo ""
echo "6. Railway will automatically redeploy"
echo ""
echo "=========================================="
echo "Configuration files created:"
echo "  - /nixpacks.toml (root level, backup)"
echo "  - /server/nixpacks.toml (will be used when root is set)"
echo "  - /Procfile (alternative start method)"
echo ""
echo "Once root directory is set to 'server', Railway will:"
echo "  - Use /server/nixpacks.toml"
echo "  - Install dependencies from /server/package.json"
echo "  - Build TypeScript to /server/dist/"
echo "  - Start with: node dist/server.js"
echo "=========================================="
