// client/src/shared/routes.ts

export const routes = {
  root: "/",
  splash: "/",
  waitlist: "/join",
  login: "/login",
  signup: "/signup",
  callback: "/callback",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  profile: "/profile",
  preseasonRank: "/preseason-rank",
  weeklyPicks: "/weekly-picks",
  weeklyResults: "/weekly-results",
  draftResults: "/draft-results",
  leaderboard: "/leaderboard",
  league: "/league",
  myLeagues: "/my-leagues",
  createLeague: "/create-league",
  joinLeague: "/join-league",
  joinSuccess: "/join-success",
  globalLeaderboard: "/global-leaderboard",
  about: "/about",
  contact: "/contact",
  rules: "/rules",
  howToPlay: "/how-to-play",
  castaway: (id: string | number) => `/castaway/${id}`,
  notFound: "*",
  admin: {
    index: "/admin",
    dashboard: "/admin",
    draft: "/admin/draft",
    picks: "/admin/draft",
    castaways: "/admin/castaways",
    users: "/admin/users",
    leagueManager: "/admin/league-manager",
    scoring: "/admin/scoring",
    season: "/admin/season",
    stats: "/admin/stats",
    analytics: "/admin/analytics",
    headToHead: "/admin/head-to-head",
    announcements: "/admin/announcements",
    feedback: "/admin/feedback",
    sms: "/admin/sms",
    scoringDashboard: "/admin/scoring-dashboard"
  }
} as const;

export type RouteKey = keyof typeof routes;
