/**
 * Job Alerting System
 *
 * Sends email and SMS alerts when scheduled jobs fail.
 * Integrated with job monitoring system to provide real-time notifications
 * for system administrators.
 */

import { enqueueEmail } from '../lib/email-queue.js';
import { sendSMS } from '../config/twilio.js';
import type { JobExecution } from './jobMonitor.js';

// Critical jobs that warrant SMS alerts (not just email)
const CRITICAL_JOBS = new Set([
  'lock-picks',      // Locks weekly picks before episode airs
  'auto-pick',       // Auto-assigns picks for users who missed deadline
  'draft-finalize',  // Finalizes draft at hard deadline
  'release-results', // Releases spoiler-safe weekly results
]);

interface AlertConfig {
  adminEmail?: string;
  adminPhone?: string;
}

let config: AlertConfig = {};

/**
 * Initialize alerting configuration
 * Should be called on server startup
 */
export function initializeAlerting(options: AlertConfig): void {
  config = {
    adminEmail: options.adminEmail || process.env.ADMIN_EMAIL,
    adminPhone: options.adminPhone || process.env.ADMIN_PHONE,
  };

  if (!config.adminEmail) {
    console.warn('[Job Alerting] ADMIN_EMAIL not configured - email alerts disabled');
  }
  if (!config.adminPhone) {
    console.warn('[Job Alerting] ADMIN_PHONE not configured - SMS alerts disabled');
  } else {
    console.log(`[Job Alerting] Initialized with admin email: ${config.adminEmail}`);
  }
}

/**
 * Send alert when a job fails
 * Called automatically by job monitoring system
 */
export async function alertJobFailure(execution: JobExecution): Promise<void> {
  const isCritical = CRITICAL_JOBS.has(execution.jobName);

  // Send email alert (all failures)
  await sendEmailAlert(execution, isCritical);

  // Send SMS alert (critical failures only)
  if (isCritical) {
    await sendSMSAlert(execution);
  }
}

/**
 * Send email alert for job failure
 */
async function sendEmailAlert(execution: JobExecution, isCritical: boolean): Promise<void> {
  if (!config.adminEmail) {
    return; // Email alerts disabled
  }

  const subject = isCritical
    ? `[RGFL] CRITICAL: Job "${execution.jobName}" Failed`
    : `[RGFL] Job Failure: ${execution.jobName}`;

  const html = `
    <h2>Scheduled Job Failure</h2>

    <p><strong>Job Name:</strong> ${execution.jobName}</p>
    <p><strong>Severity:</strong> ${isCritical ? '🚨 CRITICAL' : '⚠️ Normal'}</p>
    <p><strong>Start Time:</strong> ${execution.startTime.toISOString()}</p>
    <p><strong>End Time:</strong> ${execution.endTime?.toISOString() || 'N/A'}</p>
    <p><strong>Duration:</strong> ${execution.durationMs ? `${execution.durationMs}ms` : 'N/A'}</p>

    <h3>Error Details</h3>
    <pre style="background-color: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto;">${execution.error || 'Unknown error'}</pre>

    ${isCritical ? `
    <h3>⚠️ Critical Job - Immediate Action Required</h3>
    <p>This job is critical to the platform's operation. Please investigate immediately:</p>
    <ul>
      <li><strong>lock-picks:</strong> Ensures picks are locked before episode airs</li>
      <li><strong>auto-pick:</strong> Assigns picks for users who missed deadline</li>
      <li><strong>draft-finalize:</strong> Finalizes draft at hard deadline</li>
      <li><strong>release-results:</strong> Releases spoiler-safe weekly results to players</li>
    </ul>
    ` : ''}

    <h3>Next Steps</h3>
    <ol>
      <li>Check server logs for full stack trace</li>
      <li>Verify external service connectivity (database, APIs)</li>
      <li>Check job history: <code>GET /api/admin/jobs/history?jobName=${execution.jobName}</code></li>
      <li>Manually retry if needed: Job will retry on next scheduled run</li>
    </ol>

    <p><em>Generated by RGFL Job Monitoring System</em></p>
  `;

  const text = `
SCHEDULED JOB FAILURE

Job Name: ${execution.jobName}
Severity: ${isCritical ? 'CRITICAL' : 'Normal'}
Start Time: ${execution.startTime.toISOString()}
End Time: ${execution.endTime?.toISOString() || 'N/A'}
Duration: ${execution.durationMs ? `${execution.durationMs}ms` : 'N/A'}

Error:
${execution.error || 'Unknown error'}

${isCritical ? '⚠️ CRITICAL JOB - Immediate action required!\n' : ''}

Next Steps:
1. Check server logs for full stack trace
2. Verify external service connectivity
3. Check job history: GET /api/admin/jobs/history?jobName=${execution.jobName}
4. Manually retry if needed
  `.trim();

  try {
    await enqueueEmail({
      to: config.adminEmail,
      subject,
      html,
      text,
      type: isCritical ? 'critical' : 'normal',
    });

    console.log(`[Job Alerting] Email alert queued for ${execution.jobName} failure`);
  } catch (error) {
    console.error('[Job Alerting] Failed to enqueue email alert:', error);
  }
}

/**
 * Send SMS alert for critical job failure
 */
async function sendSMSAlert(execution: JobExecution): Promise<void> {
  if (!config.adminPhone) {
    return; // SMS alerts disabled
  }

  const message = `[RGFL] CRITICAL: Job "${execution.jobName}" failed at ${execution.startTime.toLocaleTimeString()}. Error: ${(execution.error || 'Unknown').substring(0, 100)}... Check email for details.`;

  try {
    const result = await sendSMS({
      to: config.adminPhone,
      text: message,
      isTransactional: true, // Admin system alerts are transactional
    });

    if (result.success) {
      console.log(`[Job Alerting] SMS alert sent for ${execution.jobName} failure (SID: ${result.sid})`);
    } else {
      console.error(`[Job Alerting] Failed to send SMS alert for ${execution.jobName}`);
    }
  } catch (error) {
    console.error('[Job Alerting] Error sending SMS alert:', error);
  }
}

/**
 * Send test alert to verify configuration
 * Can be called via admin endpoint for testing
 */
export async function sendTestAlert(): Promise<{ email: boolean; sms: boolean }> {
  const testExecution: JobExecution = {
    jobName: 'test-alert',
    startTime: new Date(),
    endTime: new Date(),
    durationMs: 100,
    success: false,
    error: 'This is a test alert to verify the alerting system is configured correctly.',
  };

  const results = {
    email: false,
    sms: false,
  };

  // Test email alert
  if (config.adminEmail) {
    try {
      await sendEmailAlert(testExecution, false);
      results.email = true;
    } catch (error) {
      console.error('[Job Alerting] Test email failed:', error);
    }
  }

  // Test SMS alert
  if (config.adminPhone) {
    try {
      const result = await sendSMS({
        to: config.adminPhone,
        text: '[RGFL] Test alert: Job monitoring SMS is configured correctly.',
        isTransactional: true, // Admin test alerts are transactional
      });
      results.sms = result.success;
    } catch (error) {
      console.error('[Job Alerting] Test SMS failed:', error);
    }
  }

  return results;
}

/**
 * Get current alerting configuration (for debugging)
 */
export function getAlertingConfig(): {
  emailEnabled: boolean;
  smsEnabled: boolean;
  adminEmail?: string;
  criticalJobs: string[];
} {
  return {
    emailEnabled: !!config.adminEmail,
    smsEnabled: !!config.adminPhone,
    adminEmail: config.adminEmail,
    criticalJobs: Array.from(CRITICAL_JOBS),
  };
}
